name: 'err0-check-acction'
description: 'err0 action check'
inputs:
  ERR0_JSON:
    description: 'Variable de entorno ERR0_JSON'
    required: true
  REPO_URL:
    description: 'Url of repository'
    required: true
  GH_TOKEN:
    description: 'Github token with read and write permissions'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    REPO_URL: ${{ inputs.REPO_URL }}
    ERR0_JSON: ${{ inputs.ERR0_JSON }}
    GH_TOKEN: ${{ inputs.GH_TOKEN }}
    GITHUB_REF: ${GITHUB_REF##*/}
