name: 'err0-check-acction'
description: 'err0 action check'
branding:
  icon: 'mic'
  color: 'green'
inputs:
  ERR0_JSON:
    description: 'Variable de entorno ERR0_JSON'
    required: true
  GH_TOKEN:
    description: 'Github token with read and write permissions'
    required: true
runs:
  using: 'docker'
  # image: 'docker://err0io/agent:latest'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ERR0_JSON }}
    - ${{ inputs.GH_TOKEN }}
  env:
    ERR0_JSON: ${{ inputs.ERR0_JSON }}
    GH_TOKEN: ${{ inputs.GH_TOKEN }}
