name: 'err0-check-acction'
description: 'err0 action check'
branding:
  icon: 'mic'
  color: 'green'
inputs:
  ERR0_JSON:
    description: 'Variable de entorno ERR0_JSON'
    required: true
runs:
  using: 'docker'
  image: 'err0io/agent:latest'
  args:
    - ${{ inputs.ERR0_JSON }}
  env:
    ERR0_JSON: ${{ inputs.ERR0_JSON }}
